export const enum ArtifactsNames {
  DEMO = "Demo",
  MYTHALLAR = "Mythallar",
  HALASTERS = "Halasters",
  WYVERN = "Wyvern",
  LANTERN = "Lantern",
  BLACK_DRAGON = "Black_Dragon",
  CHARM = "Charm",
  TOKEN = "Token",
  THIRST = "Thirst",
  VANGUARDS = "Vanguards",
  STANDARD = "Standard",
  FEY_EMBLEM = "Fey_Emblem",
  FROZEN = "Frozen",
  BLADES = "Blades",
  HORN = "Horn",
  MARK = "Mark",
  PALADIN_SIGIL = "Sigil",
  TIAMAT= "Tiamat"
}

export const enum ArtifactTypes {
  DEBUFF = "Debuff",
  BUFF = "Buff",
  UTILITY = "Utility",
  MITIGATION = "Mitigation",
}

export const ArtifactsList = [
  {
    label: "Demogorgon's Reach",
    shortName: ArtifactsNames.DEMO,
    priority: 2,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Mythallar Fragment",
    shortName: ArtifactsNames.MYTHALLAR,
    priority: 1,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Halaster's Blast Scepter",
    shortName: ArtifactsNames.HALASTERS,
    priority: 1,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Wyvern-Venom Coated Knives",
    shortName: ArtifactsNames.WYVERN,
    priority: 3,
    type: [ArtifactTypes.DEBUFF, ArtifactTypes.MITIGATION],
    nonStackingArtifact: [ArtifactsNames.BLADES],
  },
  {
    label: "Lantern of Revelation",
    shortName: ArtifactsNames.LANTERN,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Heart of the Black Dragon",
    shortName: ArtifactsNames.BLACK_DRAGON,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Charm of the Serpent",
    shortName: ArtifactsNames.CHARM,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Token of Chromatic Storm",
    shortName: ArtifactsNames.TOKEN,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Thirst",
    shortName: ArtifactsNames.THIRST,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Vanguard's Banner",
    shortName: ArtifactsNames.VANGUARDS,
    priority: 5,
    type: [ArtifactTypes.DEBUFF, ArtifactTypes.MITIGATION],
  },
  {
    label: "Neverwinter's Standard",
    shortName: ArtifactsNames.STANDARD,
    priority: 5,
    type: [ArtifactTypes.DEBUFF],
  },
  {
    label: "Sparkling Fey Emblem",
    shortName: ArtifactsNames.FEY_EMBLEM,
    priority: 5,
    type: [ArtifactTypes.DEBUFF, ArtifactTypes.MITIGATION],
  },
  {
    label: "Frozen Storyteller's Journal",
    shortName: ArtifactsNames.FROZEN,
    priority: 5,
    type: [ArtifactTypes.BUFF],
  },
  {
    label: "Dragonbone Blades",
    shortName: ArtifactsNames.BLADES,
    priority: 2,
    type: [ArtifactTypes.DEBUFF, ArtifactTypes.MITIGATION],
    nonStackingArtifact: [ArtifactsNames.WYVERN],
  },
  {
    label: "Horn of Valhalla",
    shortName: ArtifactsNames.HORN,
    priority: 0,
    type: [ArtifactTypes.UTILITY],
  },
  {
    label: "Sigil of the Paladin",
    shortName: ArtifactsNames.PALADIN_SIGIL,
    priority: 1,
    type: [ArtifactTypes.MITIGATION],
  },
  {
    label: "Tiamat's Orb",
    shortName: ArtifactsNames.TIAMAT,
    priority: 1,
    type: [ArtifactTypes.MITIGATION],
  },
  {
    label: "Black Dragon's Mark",
    shortName: ArtifactsNames.MARK,
    priority: 4,
    type: [ArtifactTypes.DEBUFF],
  },
];
